### ISSUE TITLE
Pre-submission checklist

### ISSUE THREAD

**Issue by grst** [LeonHafner/sc-guidelines#1]
Hi @mlist @LeonHafner, 

I usually use this list with items to tick off before submission. 

# Paper submission checklist

## Paper

- [x] check figure legends
- [x] re-read entire manuscript
- [x] all (supplementary) figures and tabled numbered in the order they appear in the manuscript
- [x] all (supplementary) figures and tables correctly referenced
- [x] check that methods contain everything represented in the manuscript and only everything in the manuscript
- [x] check results fit with the latest pipeline run (=data uploaded on zenodo)

## Code and data availability

- [x] processed data uploaded on zenodo
- [x] code on GitHub (and public)
- [x] versioned release of code (calver)
- [x] any uploaded data does not contain private data (i.e. licensed scripts, data obtained under CDA)
- [x] software packaged as singularity containers and available from zenodo/github

## Repo

- [x] Readme is sufficient to execute the code and obtain the data
- [x] LICENSE available
- [x] fix TODO comments
